vendor map toegevoegt

diff --git a/vendor/psy/psysh/Makefile b/vendor/psy/psysh/Makefile
--- a/vendor/psy/psysh/Makefile
+++ b/vendor/psy/psysh/Makefile
@@ -13,12 +13,12 @@ endif
 
 # Commands
 
-.PHONY: help build clean dist test phpstan
+.PHONY: help build clean dist test test-phar smoketest phpstan
 .DEFAULT_GOAL := help
 
 help:
 	@echo "\033[33mUsage:\033[0m\n  make TARGET\n\n\033[33mTargets:\033[0m"
-	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[32m%-7s\033[0m %s\n", $$1, $$2}'
+	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[32m%-9s\033[0m %s\n", $$1, $$2}'
 
 build: ## Compile psysh PHAR
 build: build/psysh/psysh
@@ -34,6 +34,22 @@ dist: dist/psysh-$(VERSION).tar.gz
 test: ## Run unit tests
 test: vendor/bin/phpunit
 	$< $(PHPUNIT_OPTS)
+
+test-phar: ## Run unit tests with PHAR bootstrap
+test-phar: build/psysh/psysh
+	$(eval PHAR_TEST_DIR := $(shell mktemp -d))
+	@echo "Setting up isolated test environment in $(PHAR_TEST_DIR)..."
+	@cp -r test $(PHAR_TEST_DIR)/
+	@cp $< $(PHAR_TEST_DIR)/
+	@cd $(PHAR_TEST_DIR) && \
+		COMPOSER_ROOT_VERSION=1.0.0 composer init --no-interaction --name=psy/test --autoload=test/ 2>&1 | grep -v "PSR-4" || true && \
+		COMPOSER_ROOT_VERSION=1.0.0 composer require --no-interaction --no-progress "phpunit/phpunit:^9.6" 2>&1 | grep -v "locking\|Extracting" | head -3 || true && \
+		vendor/bin/phpunit --bootstrap psysh --exclude-group isolation-fail test/
+	@rm -rf $(PHAR_TEST_DIR)
+
+smoketest: ## Run smoke tests on existing binaries
+smoketest: build/psysh/psysh
+	test/smoketest.sh
 
 phpstan: ## Run static analysis
 phpstan: vendor/bin/phpstan vendor/bin/phpunit
@@ -76,10 +92,18 @@ build/psysh: $(PSYSH_SRC) $(PSYSH_SRC_FILES)
 	rm -rf $@ || true
 	mkdir $@
 	cp -R $(PSYSH_SRC) $@/
+	@# Fetch and include latest PHP manual
+	@if bin/fetch-manual; then \
+		echo "Including bundled manual..."; \
+		cp php_manual.php $@/; \
+		rm php_manual.php; \
+	else \
+		echo "Manual fetch failed, continuing without bundled manual"; \
+	fi
 	sed -i -e "/^ *const VERSION =/ s/'.*'/'$(VERSION)'/" $@/src/Shell.php
 	composer config --working-dir $@ platform.php 7.4
 	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) php:'>=7.4'
-	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) symfony/polyfill-iconv symfony/polyfill-mbstring
+	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) symfony/polyfill-iconv symfony/polyfill-mbstring composer/class-map-generator
 	composer require --working-dir $@ $(COMPOSER_REQUIRE_OPTS) --dev roave/security-advisories:dev-latest
 	composer update --working-dir $@ $(COMPOSER_UPDATE_OPTS)
 
